- name: Get RG
  hosts: localhost
  vars_files:
    - secret
    - vars.yaml
  tasks:
  - name: get resource group info
    decort_rg:
     authenticator: "{{ authenticator }}"
     app_id: "{{ app_id }}"
     app_secret: "{{ app_secret }}"
     controller_url: "{{ controller_url }}"
     oauth2_url: "{{ oauth2_url }}"
     account_id: "{{ account_id }}"
     rg_name: "Ansible Created RG"
    register: my_rg
  - name: Display the gathered facts
    debug:
      var: my_rg.facts
